---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zdh.
--- DateTime: 2019/2/12 21:03
---

A = {}

local this = A

function A.New()
    return this
end

function A.C()
    this.a = 10
end
