---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zdh.
--- DateTime: 2018/11/4 21:52
---

print('\n\n\n\n')
print('开始测试Dictionary')

require('Dictionary.Dictionary')

local dic = Dictionary:New()

dic:Add(1,'zzz')

dic:Add(10,'ddd')

dic:Add(5,'hhh')

print('dic的存储个数为' .. dic:Count())
print([[是否包含10]] .. tostring(dic:Contain(10)))
print([[是否包含'ddd']] .. tostring(dic:Contain('ddd')))

print('开始遍历')

local  keys = dic:GetKeys()

for i = 1, #keys do
    print(dic:GetValueByKey(keys[i]))
end

for i, v in pairs(dic) do
    print(i,v)
end

print('移除一个 键值对')
dic:Remove(10)

for i, v in pairs(dic) do
    print(i,v)
end

print('dic的存储个数为' .. dic:Count())

print([[是否包含10]] .. tostring(dic:Contain(10)))


print('测试Dictionary结束')