---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zdh.
--- DateTime: 2018/11/4 21:38
---

---@class  Dictionary 字典 Dictionary
Dictionary = {}

Dictionary.__index  = Dictionary

---@type function New 构造函数
function Dictionary:New()
    local result = {}
    setmetatable(result,Dictionary)
    return result
end


---@type function Contain 是否包含
---@param key 键
---@return boolean true 是包含 false是不含
function Dictionary:Contain(key)
    return self[key] ~= nil
end

---@type function Add 添加
---@param key 键
---@param value 值
function Dictionary:Add(key,value)
    if self[key] ~=nil then
        return false
    else
        self[key] = value
        return true
    end
end

---@type function Remove 移除
---@param key 键
function Dictionary:Remove(key)
    if self:Contain(key) then
        self[key] = nil
    end
end

---@type function GetValueByKey 获取
---@param key 键
---@return 返回值
function Dictionary:GetValueByKey(key)
    if self:Contain(key) then
        return self[key]
    end
end

---@type function GetKeys 获取键的table
---@return 返回值
function Dictionary:GetKeys()
    local result= {}
    for key, value in pairs(self) do
        table.insert(result,#table+1,key)
    end
    return result
end

---@type function GetValues 获取值的table
---@return 返回值
function Dictionary:GetValues()
    local result= {}
    for key, value in pairs(self) do
        table.insert(result,#table+1,value)
    end
    return result
end

---@type function Next 迭代器
function Dictionary:Next()
    local keys = self:GetKeys()
    local temp = 1
    return function()
        if temp <= #keys then
            local result = self:GetValueByKey(keys[temp])
            temp = temp + 1
            return result
        else
            return nil
        end
    end
end

---@type function Count 获取存储的个数
---@return 返回值
function Dictionary:Count()
    local temp = self:GetKeys()
    return #temp
end

return Dictionary