---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/2 16:19
---
require("Array.Array")

print('开始测试Array')

local myArray1 = Array:New()
local myArray2 = Array:New()

print(myArray1)
print(myArray2)

myArray1:AddItemToLeft(10)
myArray1:AddItemToLeft(13)
myArray1:AddItemToLeft(9)
myArray1:AddItemToRight(32)
myArray1:AddItemToRight(14)
myArray1:AddItemToRight(10)

print('myArray1的item总数量'..myArray1:Count())
for i = myArray1:GetLeftIndex(), myArray1:GetRightIndex() do
    print('myArray1的下标为'..i ..'的值为'.. myArray1:GetItemByIndex(i))
end

print('删除一个10')
myArray1:RemoveOneItem(10)
print('myArray1的item总数量'..myArray1:Count())
for i = myArray1:GetLeftIndex(), myArray1:GetRightIndex() do
    print('myArray1的下标为'..i ..'的值为'.. myArray1:GetItemByIndex(i))
end

print('再添加一个10')
myArray1:AddItemToLeft(10)
print('myArray1的item总数量'..myArray1:Count())
for i = myArray1:GetLeftIndex(), myArray1:GetRightIndex() do
    print('myArray1的下标为'..i ..'的值为'.. myArray1:GetItemByIndex(i))
end

print('删除所有的10')
myArray1:RemoveAllItem(10)
print('myArray1的item总数量'..myArray1:Count())
for i = myArray1:GetLeftIndex(), myArray1:GetRightIndex() do
    print('myArray1的下标为'..i ..'的值为'.. myArray1:GetItemByIndex(i))
end

print('升序排序')
myArray1:SortItemByUp()
print('myArray1的item总数量'..myArray1:Count())
for i = myArray1:GetLeftIndex(), myArray1:GetRightIndex() do
    print('myArray1的下标为'..i ..'的值为'.. myArray1:GetItemByIndex(i))
end

print('降序排序')
myArray1:SortItemByDown()
print('myArray1的item总数量'..myArray1:Count())
for i = myArray1:GetLeftIndex(), myArray1:GetRightIndex() do
    print('myArray1的下标为'..i ..'的值为'.. myArray1:GetItemByIndex(i))
end


print('myArray2的item总数量'..myArray2:Count())
for i = myArray2:GetLeftIndex(), myArray2:GetRightIndex() do
    print('myArray2的下标为'..i ..'的值为'.. myArray2:GetItemByIndex(i))
end

myArray2:AddItemToLeft(10)
myArray2:AddItemToRight(31)
print('myArray2的item总数量'..myArray2:Count())
print('降序排序')
myArray2:SortItemByDown()
print('myArray2的item总数量'..myArray2:Count())
for i = myArray2:GetLeftIndex(), myArray2:GetRightIndex() do
    print('myArray2的下标为'..i ..'的值为'.. myArray2:GetItemByIndex(i))
end

print('合并2到1')
myArray1:AddRangeToLeft(myArray2)
print('myArray1的item总数量'..myArray1:Count())
for i = myArray1:GetLeftIndex(), myArray1:GetRightIndex() do
    print('myArray1的下标为'..i ..'的值为'.. myArray1:GetItemByIndex(i))
end

print('合并2到1')
myArray1:AddRangeToLeft(myArray2)
print('myArray1的item总数量'..myArray1:Count())
for i = myArray1:GetLeftIndex(), myArray1:GetRightIndex() do
    print('myArray1的下标为'..i ..'的值为'.. myArray1:GetItemByIndex(i))
end


print('测试迭代器')

local arrayNext = myArray1:Next()
local value = arrayNext()
while(value~=nil) do
    print(value)
    value = arrayNext()
end

myArray2:ClearArray()
print('myArray2的item总数量'..myArray2:Count())

print('测试Array结束')