---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/2 16:55
---

print('开始测试List')

require('List.List')

local list = List:New()

list:AddItemToLeft(10)
list:AddItemToLeft(9)
list:AddItemToRight(11)

local first = list.firstNode

while(first~=nil) do
    print(first.data)
    first = first.rightPointer
end

print('list的长度为'..list.count)

list:ClearList()

print('list的长度为'..list.count)

print('测试List结束')